Add flexibility to design
DND5/dnd pull request #17
Opened 2021-11-18 20:32 UTC by embalex

2021-11-18 22:28 UTC, akuskis requested changes

2021-11-18 22:28 UTC, akuskis commented on webui/src/uiComponents/theme/baseLine/index.ts
> +    };
Interesting endings. Here it's ";", later it's ","

2021-11-19 07:21 UTC, embalex commented on webui/src/uiComponents/theme/baseLine/index.ts
> +    };
Yep. It was a problem

2021-11-20 13:30 UTC, akuskis approved these changes

2021-11-20 13:31 UTC, merged