Add common UI
DND5/dnd pull request #7
Opened 2021-11-12 23:37 UTC by embalex

Добавлено дофига всего по clints (staff). Добавлена welcome страница. Кнопка ведет на кубики )
![image](https://user-images.githubusercontent.com/24508326/141595580-bbb7f77d-f855-449b-b29c-e4438850806c.png)

2021-11-13 08:29 UTC, akuskis commented on client/.prettierrc
> +  "printWidth": 100,
with width screens I think that 120 is fine (you can even split screen twice)

2021-11-13 09:03 UTC, embalex commented on client/.prettierrc
> +  "printWidth": 100,
It does not matter. At last project we used 100. At the end - fixed to 120.

2021-11-13 18:04 UTC, akuskis requested changes

2021-11-14 11:53 UTC, embalex commented on client/src/Features/Welcome/index.tsx
> +          sx={{
Give me the time )). Now i have no idea about best practices for mui 5. It changed technology from css-in-js to styled-components and wrap it to custom wrapper. I'll refactor it later.

2021-11-14 12:01 UTC, akuskis approved these changes

2021-11-14 12:06 UTC, merged